const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// MediaPipeTasksCommon (pulled in by MediaPipeTasksVision, which
// modules/mediapipe-face-landmarker depends on) ships prebuilt static archives
// under frameworks/graph_libraries/ that statically embed their own copies of
// GTMSessionFetcher and GoogleToolboxForMac's GTMLogger.
// react-native-vision-camera-face-detector depends on GoogleMLKit/FaceDetection,
// which links the REAL GTMSessionFetcher / GoogleToolboxForMac pods. Linking
// both is what produced `ld: 221 duplicate symbols` on the iOS archive.
//
// Both packages are genuinely used by src/components/SkinScanCamera.tsx (MLKit
// for the live face box, MediaPipe for the landmark mesh), so neither can just
// be dropped. Google's own guidance for this collision is to delete MediaPipe's
// embedded duplicates from the archive and let the real pods provide those
// symbols — the two copies are the same upstream sources, so MLKit's pod build
// satisfies MediaPipe's references.
//
// The Podfile is generated by prebuild (this project has no committed ios/
// directory), so the strip is injected into the generated Podfile's post_install
// hook rather than checked in.

const MARKER = 'glow-mediapipe-gtm-dedupe';

const SNIPPET = `
    # >>> ${MARKER} >>> (injected by plugins/withMediaPipeGtmDedupe.js)
    # Strip GTMSessionFetcher / GoogleToolboxForMac object files that
    # MediaPipeTasksCommon's prebuilt graph archives embed, so they do not
    # collide with the same symbols coming from GoogleMLKit's real pods.
    begin
      require 'tmpdir'

      duplicate_objects = %w[
        GTMSessionFetcher.o
        GTMSessionFetcherService.o
        GTMSessionUploadFetcher.o
        GTMLogger.o
      ]

      # \`ar -t\` cannot read a universal (fat) archive, so membership has to be
      # checked per-slice for those — hence the two branches below.
      list_members = lambda do |path|
        \`ar -t "#{path}" 2>/dev/null\`.split("\\n").map(&:strip)
      end

      archives = Dir.glob(File.join(installer.sandbox.root.to_s, 'MediaPipeTasks*', '**', '*.a'))
      Pod::UI.puts "[${MARKER}] scanning #{archives.count} MediaPipe archive(s)" if archives.any?

      archives.each do |archive|
        lipo_info = \`lipo -info "#{archive}" 2>/dev/null\`
        archs = lipo_info.include?('Architectures in the fat file') ? lipo_info.split(':').last.split : []

        if archs.size > 1
          Dir.mktmpdir do |tmp|
            stripped = []
            slices = archs.map do |arch|
              slice = File.join(tmp, "#{File.basename(archive, '.a')}-#{arch}.a")
              system('lipo', archive, '-thin', arch, '-output', slice, out: File::NULL, err: File::NULL)
              hits = list_members.call(slice) & duplicate_objects
              unless hits.empty?
                stripped |= hits
                system('ar', '-d', slice, *hits, out: File::NULL, err: File::NULL)
                system('ranlib', slice, out: File::NULL, err: File::NULL)
              end
              slice
            end
            next if stripped.empty?
            system('lipo', '-create', *slices, '-output', archive, out: File::NULL, err: File::NULL)
            Pod::UI.puts "[${MARKER}] stripped #{stripped.join(', ')} from #{File.basename(archive)} (#{archs.join('/')})"
          end
        else
          hits = list_members.call(archive) & duplicate_objects
          next if hits.empty?
          system('ar', '-d', archive, *hits, out: File::NULL, err: File::NULL)
          system('ranlib', archive, out: File::NULL, err: File::NULL)
          Pod::UI.puts "[${MARKER}] stripped #{hits.join(', ')} from #{File.basename(archive)}"
        end
      end
    rescue => e
      Pod::UI.warn "[${MARKER}] failed: #{e.message}"
    end
    # <<< ${MARKER} <<<
`;

function patchPodfile(contents) {
  if (contents.includes(MARKER)) {
    return contents;
  }

  const postInstall = /^(\s*post_install do \|installer\|\s*$)/m;
  if (postInstall.test(contents)) {
    return contents.replace(postInstall, `$1\n${SNIPPET}`);
  }

  // No post_install hook in the generated Podfile (not expected for an Expo
  // template, but do not silently drop the fix if the template ever changes) —
  // append our own at the bottom instead.
  return `${contents}\n\npost_install do |installer|\n${SNIPPET}\nend\n`;
}

module.exports = function withMediaPipeGtmDedupe(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');
      const patched = patchPodfile(contents);
      if (patched !== contents) {
        fs.writeFileSync(podfilePath, patched);
      }
      return cfg;
    },
  ]);
};
